export const TOPICS = {
  "Dynamic Programming": 1,
  "Topological Sort": 1,
  "Prefix Sum": 1,
  Quickselect: 1,
  "Bit Manipulation": 1,
  "Merge Sort": 1,
  "Binary Search Tree": 1,
  Enumeration: 1,
  "Ordered Set": 1,
  "Binary Tree": 1,
  "Strongly Connected Component": 1,
  Counting: 1,
  Sorting: 1,
  Backtracking: 1,
  "Two Pointers": 1,
  Simulation: 1,
  "Binary Search": 1,
  Matrix: 1,
  Geometry: 1,
  "Eulerian Circuit": 1,
  "Monotonic Queue": 1,
  "Segment Tree": 1,
  Interactive: 1,
  Combinatorics: 1,
  Math: 1,
  Shell: 1,
  Stack: 1,
  "Radix Sort": 1,
  "Suffix Array": 1,
  Randomized: 1,
  Array: 1,
  "Divide and Conquer": 1,
  "Heap (Priority Queue)": 1,
  "Counting Sort": 1,
  "Probability and Statistics": 1,
  "Breadth-First Search": 1,
  "Line Sweep": 1,
  Database: 1,
  "Depth-First Search": 1,
  "Game Theory": 1,
  "String Matching": 1,
  Trie: 1,
  "Minimum Spanning Tree": 1,
  "Sliding Window": 1,
  "Bucket Sort": 1,
  Queue: 1,
  "Hash Table": 1,
  "Rejection Sampling": 1,
  Graph: 1,
  "Doubly-Linked List": 1,
  "Shortest Path": 1,
  Tree: 1,
  "Rolling Hash": 1,
  Bitmask: 1,
  Concurrency: 1,
  Design: 1,
  "Binary Indexed Tree": 1,
  "Data Stream": 1,
  "Number Theory": 1,
  "Hash Function": 1,
  "Biconnected Component": 1,
  Greedy: 1,
  "Union Find": 1,
  "Linked List": 1,
  "Monotonic Stack": 1,
  "Reservoir Sampling": 1,
  Memoization: 1,
  Iterator: 1,
  String: 1,
  Brainteaser: 1,
  Recursion: 1,
}; // To update with final list
export const DIFFICULTIES = { Easy: 1, Medium: 1, Hard: 1 };
